version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: Zxcvbnm123
      POSTGRES_DB: fortest
    ports:
      - "5432:5432"

  fortest:
    build: .
    ports:
      - "8889:8889"
    environment:
      DATABASE_URL: postgres://postgres:Zxcvbnm123@62.72.23.250:5432/fortest
    depends_on:
      - db
    restart: always
